export const samplePreparations = [
  {
    "id": "prep_store_osmocote_bloom",
    "name": "Osmocote Bloom (для петуній) до 3 місяців (0,5 кг)",
    "category": "fertilizer",
    "image": "./src/assets/preparations/prep_store_osmocote_bloom.webp",
    "dosage": "Уточнить по инструкции препарата перед применением",
    "description": "Упаковка: пакет 0,5 кг. Дозировка: Уточнить по инструкции препарата перед применением. Назначение: для квітучих рослин у невеликих контейнерах із циклом 6-12 тижнів."
  },
  {
    "id": "prep_store_kaltsinit_kaltsievaya_selitra",
    "name": "Кальцієва Селітра (Кальциніт) ВИРОБНИК YARA (0,5 кг)",
    "category": "fertilizer",
    "image": "./src/assets/preparations/prep_store_kaltsinit_kaltsievaya_selitra.webp",
    "dosage": "1 столова ложка (приблизно 25 г) на 10 л води",
    "description": "Упаковка: пакет 0,5 кг. Дозировка: 1 столова ложка (приблизно 25 г) на 10 л води. Назначение: для підживлення кальцієм і профілактики кальцієвого дефіциту."
  },
  {
    "id": "prep_master_202020",
    "name": "Мастер NPK 20-20-20 Valagro (0,5 кг)",
    "category": "fertilizer",
    "image": "./src/assets/preparations/prep_master_202020.webp",
    "dosage": "1 ст. ложка на 10 л води (під корінь)",
    "description": "Упаковка: пакет 0,5 кг. Дозировка: 1 ст. ложка на 10 л води (під корінь). Назначение: для регулярного кореневого підживлення квітів, розсади й овочів."
  },
  {
    "id": "prep_store_monofosfat_kaliya",
    "name": "Монофосфат Калію ВИРОБНИК YARA NPK 0-52-34 (0,5 кг)",
    "category": "fertilizer",
    "image": "./src/assets/preparations/prep_store_monofosfat_kaliya.webp",
    "dosage": "1 столова ложка (приблизно 25 г) на 10 л води",
    "description": "Упаковка: пакет 0,5 кг. Дозировка: 1 столова ложка (приблизно 25 г) на 10 л води. Назначение: для кореневого та листкового підживлення розсади, квітів і овочів."
  },
  {
    "id": "prep_store_plantafol_20_20_20",
    "name": "Plantafol 20.20.20 Valagro (0,25 кг)",
    "category": "fertilizer",
    "image": "./src/assets/preparations/prep_store_plantafol_20_20_20.webp",
    "dosage": "1 ст. ложка на 10 л води (по листу)",
    "description": "Упаковка: пакет 0,25 кг. Дозировка: 1 ст. ложка на 10 л води (по листу). Назначение: для листкового підживлення під час активної вегетації."
  },
  {
    "id": "prep_store_brexil_ca",
    "name": "Brexil Ca Valagro (100 г)",
    "category": "fertilizer",
    "image": "./src/assets/preparations/prep_store_brexil_ca.webp",
    "dosage": "15-20 г на 10 л води",
    "description": "Упаковка: розфасовано в 100 г пакетик. Дозировка: 15-20 г на 10 л води. Назначение: для листкового внесення при нестачі кальцію та ризику вершинної гнилі."
  },
  {
    "id": "prep_store_brexil_mix",
    "name": "Brexil MIX Valagro (100 г)",
    "category": "fertilizer",
    "image": "./src/assets/preparations/prep_store_brexil_mix.webp",
    "dosage": "10-20 г на 10 л води",
    "description": "Упаковка: розфасовано в 100 г пакетик. Дозировка: 10-20 г на 10 л води. Назначение: для корекції нестачі мікроелементів через листок."
  },
  {
    "id": "prep_vertimek",
    "name": "Вертімек 018-ЄС (10 мл)",
    "category": "insecticide",
    "image": "./src/assets/preparations/prep_vertimek.webp",
    "dosage": "для квітів і овочів: 2 мл на 1 л води (по листу)",
    "waitingPeriod": "7 дней (овощи, клубника), 14 дней (яблоня)",
    "description": "Упаковка: 10 мл. Дозировка: для квітів і овочів: 2 мл на 1 л води (по листу). Назначение: проти кліщів, мінерів, трипсів, попелиць і медяниць."
  },
  {
    "id": "prep_previkur",
    "name": "Магнікур Енерджи Превікур (10 мл)",
    "category": "fungicide",
    "image": "./src/assets/preparations/prep_previkur.webp",
    "dosage": "1,5 мл на 1 л води (під корінь або по листу)",
    "waitingPeriod": "20 дней",
    "description": "Упаковка: розфасований в герметичну бутилочку 10 мл. Дозировка: 1,5 мл на 1 л води (під корінь або по листу). Назначение: проти кореневих гнилей, чорної ніжки та пероноспорозу."
  },
  {
    "id": "prep_store_ukorinyuvach_ryzopon",
    "name": "Ризопон (10 г)",
    "category": "stimulant",
    "image": "./src/assets/preparations/prep_store_ukorinyuvach_ryzopon.webp",
    "dosage": "Уточнить по инструкции препарата перед применением",
    "description": "Упаковка: розфасовано в 10 г пакетики. Дозировка: Уточнить по инструкции препарата перед применением. Назначение: для вкорінення живців декоративних і плодових культур."
  },
  {
    "id": "prep_store_teppeki_teppeki_insektitsid",
    "name": "Теппекі 50 wg (3 гр)",
    "category": "insecticide",
    "image": "./src/assets/preparations/prep_store_teppeki_teppeki_insektitsid.webp",
    "dosage": "3 г на 10 л води (по листу)",
    "waitingPeriod": "до 30 дней",
    "description": "Упаковка: 3 г (розфасовано в дрібні пакетики). Дозировка: 3 г на 10 л води (по листу). Назначение: проти попелиць і білокрилки на овочевих, декоративних та інших культурах."
  },
  {
    "id": "prep_store_biostimulyator_radifarm",
    "name": "Радіфарм+ (25 мл)",
    "category": "stimulant",
    "image": "./src/assets/preparations/prep_store_biostimulyator_radifarm.webp",
    "dosage": "25 мл на 10 л води (під корінь)",
    "description": "Упаковка: 25 мл. Дозировка: 25 мл на 10 л води (під корінь). Назначение: для розвитку коренів і зменшення стресу після пересаджування."
  },
  {
    "id": "prep_megafol",
    "name": "Мегафол+ 25 мл Valagro",
    "category": "stimulant",
    "image": "./src/assets/preparations/prep_megafol.webp",
    "dosage": "2,5 мл на 1 л води (по листу)",
    "description": "Упаковка: 25 мл. Дозировка: 2,5 мл на 1 л води (по листу). Назначение: для відновлення після пересадки, спеки, холоду, граду, гербіцидного або іншого стресу."
  },
  {
    "id": "prep_store_biostymulyator_izabion",
    "name": "Ізабіон Syngenta 20 мл",
    "category": "stimulant",
    "image": "./src/assets/preparations/prep_store_biostymulyator_izabion.webp",
    "dosage": "20 мл на 5 л води",
    "description": "Упаковка: 20 мл. Дозировка: 20 мл на 5 л води. Назначение: для росту, відновлення після стресу, цвітіння та формування плодів."
  },
  {
    "id": "prep_store_prylypach_glyusten",
    "name": "Глюстен 25 мл Syngenta",
    "category": "adjuvant",
    "image": "./src/assets/preparations/prep_store_prylypach_glyusten.webp",
    "dosage": "25 мл на 10 л води",
    "description": "Упаковка: 25 мл. Дозировка: 25 мл на 10 л води. Назначение: для покращення змочування, розподілу і поглинання ЗЗР."
  },
  {
    "id": "prep_store_kvantum_quantum",
    "name": "Квантум / QUANTUM (10 мл)",
    "category": "adjuvant",
    "image": "./src/assets/preparations/prep_store_kvantum_quantum.webp",
    "dosage": "10 мл на 10 л води",
    "description": "Упаковка: 10 мл. Дозировка: 10 мл на 10 л води. Назначение: для кращого покриття листка робочим розчином."
  },
  {
    "id": "prep_store_protrujnyk_antyhrushh",
    "name": "Антихрущ (10 мл) Укравіт",
    "category": "insecticide",
    "image": "./src/assets/preparations/prep_store_protrujnyk_antyhrushh.webp",
    "dosage": "10 мл на 3–10 л води залежно від культури",
    "waitingPeriod": "30 дней",
    "description": "Упаковка: 10 мл. Дозировка: 10 мл на 3–10 л води залежно від культури. Назначение: проти ґрунтових шкідників, личинок хрущів, дротяників, капустянки та частини наземних шкідників."
  },
  {
    "id": "prep_store_sanmajt",
    "name": "Санмайт акарицид (9 г)",
    "category": "insecticide",
    "image": "./src/assets/preparations/prep_store_sanmajt.webp",
    "dosage": "1 г на 1 л води",
    "waitingPeriod": "30 дней",
    "description": "Упаковка: 9 г. Дозировка: 1 г на 1 л води. Назначение: проти рослиноїдних кліщів на різних стадіях розвитку."
  },
  {
    "id": "prep_store_aktelik",
    "name": "Актелік (6 мл)",
    "category": "insecticide",
    "image": "./src/assets/preparations/prep_store_aktelik.webp",
    "dosage": "6 мл на 5 л води",
    "waitingPeriod": "14 дней",
    "description": "Упаковка: 6 мл. Дозировка: 6 мл на 5 л води. Назначение: проти широкого спектра шкідників, зокрема приховано живучих."
  },
  {
    "id": "prep_store_ampligo",
    "name": "Ампліго, 4 мл ( від тлі та ін шкідників)",
    "category": "insecticide",
    "image": "./src/assets/preparations/prep_store_ampligo.webp",
    "dosage": "4 мл на 5 л води (по листу)",
    "waitingPeriod": "14 дней",
    "description": "Упаковка: 4 мл. Дозировка: 4 мл на 5 л води (по листу). Назначение: проти лускокрилих, попелиць, цикадок та інших шкідників за культурами реєстрації."
  },
  {
    "id": "prep_store_proklejm_4_g_syngenta_insektytsyd_zahyst_vid_lystogryzuchyh_shkidnykiv",
    "name": "Проклейм 4 г",
    "category": "insecticide",
    "image": "./src/assets/preparations/prep_store_proklejm_4_g_syngenta_insektytsyd_zahyst_vid_lystogryzuchyh_shkidnykiv.webp",
    "dosage": "4 г на 5 л води",
    "waitingPeriod": "7 дней",
    "description": "Упаковка: 4 г. Дозировка: 4 г на 5 л води. Назначение: проти листогризучих шкідників, особливо гусениць лускокрилих."
  },
  {
    "id": "prep_store_insektytsyd_enzhio",
    "name": "Енжіо (3,6 мл) Syngenta",
    "category": "insecticide",
    "image": "./src/assets/preparations/prep_store_insektytsyd_enzhio.webp",
    "dosage": "3,6 мл на 10 л води",
    "waitingPeriod": "14 дней",
    "description": "Упаковка: 3,6 мл. Дозировка: 3,6 мл на 10 л води. Назначение: для комплексного захисту від сисних і листогризучих шкідників."
  },
  {
    "id": "prep_store_insektytsyd_tempo",
    "name": "Темпо (3 г)",
    "category": "insecticide",
    "image": "./src/assets/preparations/prep_store_insektytsyd_tempo.webp",
    "dosage": "3 г на 8-10 л води",
    "waitingPeriod": "14 дней",
    "description": "Упаковка: 3 г. Дозировка: 3 г на 8-10 л води. Назначение: проти попелиць, білокрилки, трипсів і щитівок."
  },
  {
    "id": "prep_aktara",
    "name": "Актара (1,4 г)",
    "category": "insecticide",
    "image": "./src/assets/preparations/prep_aktara.webp",
    "dosage": "1,4 г на 4 л води (під корінь або по листу)",
    "waitingPeriod": "7-10 дней",
    "description": "Упаковка: 1,4 г. Дозировка: 1,4 г на 4 л води (під корінь або по листу). Назначение: проти сисних і частини листогризучих шкідників, можливе листкове та ґрунтове застосування за регламентом."
  },
  {
    "id": "prep_store_ridomil_gold_fungitsyd",
    "name": "Рідоміл Голд фунгіцид (25 г)",
    "category": "fungicide",
    "image": "./src/assets/preparations/prep_store_ridomil_gold_fungitsyd.webp",
    "dosage": "Уточнить по инструкции препарата перед применением",
    "waitingPeriod": "10-14 дней",
    "description": "Упаковка: 25 г. Дозировка: Уточнить по инструкции препарата перед применением. Назначение: проти фітофторозу, пероноспорозу та альтернаріозу за культурами реєстрації."
  },
  {
    "id": "prep_store_fungitsyd_svitch",
    "name": "Світч 10 г Syngenta",
    "category": "fungicide",
    "image": "./src/assets/preparations/prep_store_fungitsyd_svitch.webp",
    "dosage": "10 г на 5–10 л води залежно від культури",
    "waitingPeriod": "7 дней",
    "description": "Упаковка: 10 г. Дозировка: 10 г на 5–10 л води залежно від культури. Назначение: проти сірої та плодової гнилей, плямистостей і частини інших грибкових хвороб за культурами реєстрації."
  },
  {
    "id": "prep_store_kvadris",
    "name": "Квадріс (6 мл)",
    "category": "fungicide",
    "image": "./src/assets/preparations/prep_store_kvadris.webp",
    "dosage": "6 мл на 5 л води (по листу)",
    "waitingPeriod": "5 дней",
    "description": "Упаковка: 6 мл. Дозировка: 6 мл на 5 л води (по листу). Назначение: проти грибкових хвороб овочевих, плодових і декоративних культур за інструкцією."
  },
  {
    "id": "prep_store_fungitsyd_revus_top",
    "name": "Ревус Топ (6 мл)",
    "category": "fungicide",
    "image": "./src/assets/preparations/prep_store_fungitsyd_revus_top.webp",
    "dosage": "6 мл на 5 л води",
    "waitingPeriod": "14 дней",
    "description": "Упаковка: 6 мл. Дозировка: 6 мл на 5 л води. Назначение: проти альтернаріозу і фітофторозу картоплі та інших листових хвороб за регламентом."
  },
  {
    "id": "prep_store_fungitsyd_signum",
    "name": "Сігнум 6 г Яровіт Сервіс (BASF)",
    "category": "fungicide",
    "image": "./src/assets/preparations/prep_store_fungitsyd_signum.webp",
    "dosage": "6 г на 5 л води",
    "waitingPeriod": "14 дней",
    "description": "Упаковка: 6 г. Дозировка: 6 г на 5 л води. Назначение: проти альтернаріозу, сірої гнилі, плямистостей та інших хвороб за культурами реєстрації."
  },
  {
    "id": "prep_topas",
    "name": "Топаз (3 мл)",
    "category": "fungicide",
    "image": "./src/assets/preparations/prep_topas.webp",
    "dosage": "Уточнить по инструкции препарата перед применением",
    "waitingPeriod": "14 дней",
    "description": "Упаковка: 3 мл. Дозировка: Уточнить по инструкции препарата перед применением. Назначение: проти борошнистої роси та частини інших грибкових хвороб."
  },
  {
    "id": "prep_store_horus_fungitsyd",
    "name": "Хорус фунгіцид, 3 г",
    "category": "fungicide",
    "image": "./src/assets/preparations/prep_store_horus_fungitsyd.webp",
    "dosage": "Уточнить по инструкции препарата перед применением",
    "waitingPeriod": "7 дней",
    "description": "Упаковка: 3 г. Дозировка: Уточнить по инструкции препарата перед применением. Назначение: для ранньовесняного захисту плодових від комплексу хвороб."
  },
  {
    "id": "prep_store_skor",
    "name": "Скор (2 мл)",
    "category": "fungicide",
    "image": "./src/assets/preparations/prep_store_skor.webp",
    "dosage": "3-5 мл на 10 л води (3 мл профілактично, 5 мл при ознаках хвороби)",
    "waitingPeriod": "14 дней",
    "description": "Упаковка: 2 мл. Дозировка: 3-5 мл на 10 л води (3 мл профілактично, 5 мл при ознаках хвороби). Назначение: проти комплексу хвороб яблуні, груші, персика, томатів, картоплі та інших культур за даними Syngenta."
  },
  {
    "id": "prep_boro_plus",
    "name": "Боро Плюс",
    "category": "fertilizer",
    "image": "",
    "dosage": "Уточнить по инструкции препарата перед применением",
    "description": "Упаковка: не указана. Дозировка: Уточнить по инструкции препарата перед применением. Назначение: Борная подкормка для клубники и культур, где важно цветение и завязь."
  }
];

export const samplePlants = [
  {
    id: "plant_petunia",
    name: "Петунии",
    type: "flower",
    planted: "2026-05-04",
    location: "Цветы",
    notes: "Есть запись обработки 4 мая баковой смесью Топас + Вертимек + Мегафол. Следующая повторная обработка стоит на 18 мая.",
    tasks: [
      {
        id: "task_petunia_treat_20260518",
        type: "treat",
        preparationIds: ["prep_topas", "prep_vertimek", "prep_megafol"],
        nextDate: "2026-05-18",
        interval: 14,
        repeat: false,
        notes: "Повторная обработка после баковой смеси Топас + Вертимек + Мегафол от 4 мая.",
      },
    ],
  },
  {
    id: "plant_catharanthus",
    name: "Катарантусы",
    type: "flower",
    planted: "2026-05-18",
    location: "Цветы",
    notes: "Добавлены как текущая культура. Отдельные работы пока не заведены.",
    tasks: [],
  },
  {
    id: "plant_begonia",
    name: "Бегонии",
    type: "flower",
    planted: "2026-05-18",
    location: "Цветы",
    notes: "Добавлены как текущая культура. Отдельные работы пока не заведены.",
    tasks: [],
  },
  {
    id: "plant_tomato_pepper",
    name: "Томаты и перцы",
    type: "veg",
    planted: "2026-05-17",
    location: "Открытый грунт",
    notes: "Высадка рассады в открытый грунт 17 мая. В календаре уже были Мегафол, Актара + Превикур и дальнейшая подкормка Мастером.",
    tasks: [
      {
        id: "task_tomato_pepper_previkur_20260520",
        type: "treat",
        preparationIds: ["prep_aktara", "prep_previkur"],
        nextDate: "2026-05-20",
        interval: 14,
        repeat: false,
        notes: "Обработка рассады Превикуром по записи календаря.",
      },
      {
        id: "task_tomato_pepper_master_20260527",
        type: "feed",
        preparationIds: ["prep_master_202020"],
        nextDate: "2026-05-27",
        interval: 10,
        repeat: false,
        notes: "Мастер 20-20-20 для рассады, высаженной 17 мая; совместить с обработкой от болезней и вредителей.",
      },
    ],
  },
  {
    id: "plant_cucumber",
    name: "Огурцы",
    type: "veg",
    planted: "2026-05-18",
    location: "Овощи",
    notes: "Добавлены как текущая культура. Отдельные работы пока не заведены.",
    tasks: [],
  },
  {
    id: "plant_corn",
    name: "Кукуруза",
    type: "veg",
    planted: "2026-05-18",
    location: "Овощи",
    notes: "Добавлена как текущая культура. Отдельные работы пока не заведены.",
    tasks: [],
  },
  {
    id: "plant_strawberry",
    name: "Клубника",
    type: "other",
    planted: "2026-05-05",
    location: "Ягодник",
    notes: "В календаре зафиксированы подкормки Боро Плюс 5 и 15 мая.",
    tasks: [],
  },
  {
    id: "plant_rose",
    name: "Розы",
    type: "flower",
    planted: "2026-05-06",
    location: "Цветы",
    notes: "В календаре зафиксирована обработка Топас + Вертимек 6 мая.",
    tasks: [],
  },
  {
    id: "cat_site_feed_zzr",
    name: "ПІДКОРМКИ і ЗЗР",
    type: "other",
    icon: "test-tube",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 32 товара.",
    tasks: [],
  },
  {
    id: "cat_site_vegetables",
    name: "ОВОЧІ",
    type: "veg",
    icon: "tomato",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 37 товаров.",
    tasks: [],
  },
  {
    id: "cat_site_alissum",
    name: "Алісум",
    type: "flower",
    icon: "blossom",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 3 товара.",
    tasks: [],
  },
  {
    id: "cat_site_bakopa",
    name: "Бакопа",
    type: "flower",
    icon: "blossom",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 4 товара.",
    tasks: [],
  },
  {
    id: "cat_site_balsamins",
    name: "Бальзаміни Новогвінейські",
    type: "flower",
    icon: "hibiscus",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 12 товаров.",
    tasks: [],
  },
  {
    id: "cat_site_marigold",
    name: "Бархатці",
    type: "flower",
    icon: "sunflower",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 3 товара.",
    tasks: [],
  },
  {
    id: "cat_site_begonii",
    name: "Бегонії",
    type: "flower",
    icon: "rose",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 23 товара.",
    tasks: [],
  },
  {
    id: "cat_site_verbena",
    name: "Вербени",
    type: "flower",
    icon: "blossom",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 8 товаров.",
    tasks: [],
  },
  {
    id: "cat_site_dihondra",
    name: "Діхондра",
    type: "flower",
    icon: "herb",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 4 товара.",
    tasks: [],
  },
  {
    id: "cat_site_eustoma",
    name: "Еустома Махрова",
    type: "flower",
    icon: "rose",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 4 товара.",
    tasks: [],
  },
  {
    id: "cat_site_lobelia",
    name: "Лобелія",
    type: "flower",
    icon: "blossom",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 6 товаров.",
    tasks: [],
  },
  {
    id: "cat_site_osteospermum",
    name: "Остеоспермум",
    type: "flower",
    icon: "sunflower",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 2 товара.",
    tasks: [],
  },
  {
    id: "cat_site_pelargonii",
    name: "Пеларгонії",
    type: "flower",
    icon: "hibiscus",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 2 товара.",
    tasks: [],
  },
  {
    id: "cat_site_petunia_amp",
    name: "Петунії Ампельні",
    type: "flower",
    icon: "blossom",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 55 товаров.",
    tasks: [],
  },
  {
    id: "cat_site_petunia_large",
    name: "Петунії Крупноквіткові",
    type: "flower",
    icon: "blossom",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 62 товара.",
    tasks: [],
  },
  {
    id: "cat_site_petunia_double",
    name: "Петунії Махрові",
    type: "flower",
    icon: "blossom",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 10 товаров.",
    tasks: [],
  },
  {
    id: "cat_site_katarantusy",
    name: "Катарантуси",
    type: "flower",
    icon: "hibiscus",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 7 товаров.",
    tasks: [],
  },
  {
    id: "cat_site_other_flowers",
    name: "Інші квіти",
    type: "flower",
    icon: "seedling",
    planted: "2026-05-18",
    location: "Категорія сайту",
    notes: "Живая категория сайта seeds.dp.ua. Сейчас в категории 9 товаров.",
    tasks: [],
  },
];

export const sampleLog = [
  {
    id: "log_petunia_treat_20260504",
    plantId: "plant_petunia",
    plantName: "Петунии",
    taskType: "treat",
    preparationIds: ["prep_topas", "prep_vertimek", "prep_megafol"],
    doneDate: "2026-05-04",
    note: "Топас + Вертимек + Мегафол. Обработка петуний и овощей.",
    nextScheduled: "2026-05-18",
  },
  {
    id: "log_strawberry_boro_20260505",
    plantId: "plant_strawberry",
    plantName: "Клубника",
    taskType: "feed",
    preparationIds: ["prep_boro_plus"],
    doneDate: "2026-05-05",
    note: "Боро Плюс, листовая/корневая подкормка.",
    nextScheduled: "2026-05-15",
  },
  {
    id: "log_rose_treat_20260506",
    plantId: "plant_rose",
    plantName: "Розы",
    taskType: "treat",
    preparationIds: ["prep_topas", "prep_vertimek"],
    doneDate: "2026-05-06",
    note: "Топас + Вертимек.",
    nextScheduled: "",
  },
  {
    id: "log_tomato_pepper_megafol_20260515",
    plantId: "plant_tomato_pepper",
    plantName: "Томаты и перцы",
    taskType: "treat",
    preparationIds: ["prep_megafol"],
    doneDate: "2026-05-15",
    note: "Мегафол от стресса за день до высадки.",
    nextScheduled: "",
  },
  {
    id: "log_strawberry_boro_20260515",
    plantId: "plant_strawberry",
    plantName: "Клубника",
    taskType: "feed",
    preparationIds: ["prep_boro_plus"],
    doneDate: "2026-05-15",
    note: "Повторная подкормка Боро Плюс после 5 мая.",
    nextScheduled: "",
  },
  {
    id: "log_tomato_pepper_aktara_previkur_20260515",
    plantId: "plant_tomato_pepper",
    plantName: "Томаты и перцы",
    taskType: "treat",
    preparationIds: ["prep_aktara", "prep_previkur"],
    doneDate: "2026-05-15",
    note: "Пролив препаратами Актара + Превикур.",
    nextScheduled: "2026-05-20",
  },
  {
    id: "log_tomato_pepper_plant_20260517",
    plantId: "plant_tomato_pepper",
    plantName: "Томаты и перцы",
    taskType: "plant",
    doneDate: "2026-05-17",
    note: "Высадка рассады томатов и перца в открытый грунт.",
    nextScheduled: "",
  },
];
