export const samplePreparations = [
  {
    id: "prep_topas",
    name: "Топас",
    category: "fungicide",
    image: "",
    description: "Фунгицид для обработок от грибковых болезней. В календаре используется для петуний и роз.",
  },
  {
    id: "prep_vertimek",
    name: "Вертимек",
    category: "insecticide",
    image: "",
    description: "Инсекто-акарицид для защиты от вредителей. Часто идет в баковой смеси с фунгицидом.",
  },
  {
    id: "prep_megafol",
    name: "Мегафол",
    category: "stimulant",
    image: "",
    description: "Антистрессовый стимулятор после пересадки, жары или обработки.",
  },
  {
    id: "prep_aktara",
    name: "Актара",
    category: "insecticide",
    image: "",
    description: "Системный инсектицид для защиты рассады и молодых растений от вредителей.",
  },
  {
    id: "prep_previkur",
    name: "Превикур",
    category: "fungicide",
    image: "",
    description: "Фунгицид для пролива и защиты рассады от корневых гнилей и болезней.",
  },
  {
    id: "prep_master_202020",
    name: "Мастер 20-20-20",
    category: "fertilizer",
    image: "",
    description: "Комплексная подкормка для роста и восстановления после высадки.",
  },
  {
    id: "prep_boro_plus",
    name: "Боро Плюс",
    category: "fertilizer",
    image: "",
    description: "Борная подкормка для клубники и культур, где важно цветение и завязь.",
  },
];

export const samplePlants = [
  {
    id: "plant_petunia",
    name: "Петунии",
    type: "flower",
    planted: "2026-05-04",
    location: "Цветы",
    notes: "Есть запись обработки 4 мая баковой смесью Топас + Вертимек + Мегафол. Следующая повторная обработка стоит на 18 мая.",
    tasks: [
      {
        id: "task_petunia_treat_20260518",
        type: "treat",
        preparationId: "prep_topas",
        nextDate: "2026-05-18",
        interval: 14,
        repeat: false,
        notes: "Повторная обработка после баковой смеси Топас + Вертимек + Мегафол от 4 мая.",
      },
    ],
  },
  {
    id: "plant_catharanthus",
    name: "Катарантусы",
    type: "flower",
    planted: "2026-05-18",
    location: "Цветы",
    notes: "Добавлены как текущая культура. Отдельные работы пока не заведены.",
    tasks: [],
  },
  {
    id: "plant_begonia",
    name: "Бегонии",
    type: "flower",
    planted: "2026-05-18",
    location: "Цветы",
    notes: "Добавлены как текущая культура. Отдельные работы пока не заведены.",
    tasks: [],
  },
  {
    id: "plant_tomato_pepper",
    name: "Томаты и перцы",
    type: "veg",
    planted: "2026-05-17",
    location: "Открытый грунт",
    notes: "Высадка рассады в открытый грунт 17 мая. В календаре уже были Мегафол, Актара + Превикур и дальнейшая подкормка Мастером.",
    tasks: [
      {
        id: "task_tomato_pepper_previkur_20260520",
        type: "treat",
        preparationId: "prep_previkur",
        nextDate: "2026-05-20",
        interval: 14,
        repeat: false,
        notes: "Обработка рассады Превикуром по записи календаря.",
      },
      {
        id: "task_tomato_pepper_master_20260527",
        type: "feed",
        preparationId: "prep_master_202020",
        nextDate: "2026-05-27",
        interval: 10,
        repeat: false,
        notes: "Мастер 20-20-20 для рассады, высаженной 17 мая; совместить с обработкой от болезней и вредителей.",
      },
    ],
  },
  {
    id: "plant_cucumber",
    name: "Огурцы",
    type: "veg",
    planted: "2026-05-18",
    location: "Овощи",
    notes: "Добавлены как текущая культура. Отдельные работы пока не заведены.",
    tasks: [],
  },
  {
    id: "plant_corn",
    name: "Кукуруза",
    type: "veg",
    planted: "2026-05-18",
    location: "Овощи",
    notes: "Добавлена как текущая культура. Отдельные работы пока не заведены.",
    tasks: [],
  },
  {
    id: "plant_strawberry",
    name: "Клубника",
    type: "other",
    planted: "2026-05-05",
    location: "Ягодник",
    notes: "В календаре зафиксированы подкормки Боро Плюс 5 и 15 мая.",
    tasks: [],
  },
  {
    id: "plant_rose",
    name: "Розы",
    type: "flower",
    planted: "2026-05-06",
    location: "Цветы",
    notes: "В календаре зафиксирована обработка Топас + Вертимек 6 мая.",
    tasks: [],
  },
];

export const sampleLog = [
  {
    id: "log_petunia_treat_20260504",
    plantId: "plant_petunia",
    plantName: "Петунии",
    taskType: "treat",
    preparationId: "prep_topas",
    doneDate: "2026-05-04",
    note: "Топас + Вертимек + Мегафол. Обработка петуний и овощей.",
    nextScheduled: "2026-05-18",
  },
  {
    id: "log_strawberry_boro_20260505",
    plantId: "plant_strawberry",
    plantName: "Клубника",
    taskType: "feed",
    preparationId: "prep_boro_plus",
    doneDate: "2026-05-05",
    note: "Боро Плюс, листовая/корневая подкормка.",
    nextScheduled: "2026-05-15",
  },
  {
    id: "log_rose_treat_20260506",
    plantId: "plant_rose",
    plantName: "Розы",
    taskType: "treat",
    preparationId: "prep_topas",
    doneDate: "2026-05-06",
    note: "Топас + Вертимек.",
    nextScheduled: "",
  },
  {
    id: "log_tomato_pepper_megafol_20260515",
    plantId: "plant_tomato_pepper",
    plantName: "Томаты и перцы",
    taskType: "treat",
    preparationId: "prep_megafol",
    doneDate: "2026-05-15",
    note: "Мегафол от стресса за день до высадки.",
    nextScheduled: "",
  },
  {
    id: "log_strawberry_boro_20260515",
    plantId: "plant_strawberry",
    plantName: "Клубника",
    taskType: "feed",
    preparationId: "prep_boro_plus",
    doneDate: "2026-05-15",
    note: "Повторная подкормка Боро Плюс после 5 мая.",
    nextScheduled: "",
  },
  {
    id: "log_tomato_pepper_aktara_previkur_20260515",
    plantId: "plant_tomato_pepper",
    plantName: "Томаты и перцы",
    taskType: "treat",
    preparationId: "prep_previkur",
    doneDate: "2026-05-15",
    note: "Пролив препаратами Актара + Превикур.",
    nextScheduled: "2026-05-20",
  },
  {
    id: "log_tomato_pepper_plant_20260517",
    plantId: "plant_tomato_pepper",
    plantName: "Томаты и перцы",
    taskType: "plant",
    doneDate: "2026-05-17",
    note: "Высадка рассады томатов и перца в открытый грунт.",
    nextScheduled: "",
  },
];
